spring:
  main:
    web-application-type: none
  config:
    import:
      - "optional:file:./config/base.yml"
      - "optional:file:./config/exchanges/binance.yml"
      - "optional:file:./config/exchanges/mexc.yml"
      - "optional:file:./config/exchanges/xt.yml"
      - "optional:file:./config/exchanges/coinex.yml"
      - "optional:file:./config/exchanges/bitmart.yml"
      - "optional:file:./config/exchanges/kucoin.yml"
      - "optional:file:./config/exchanges/gateio.yml"
      - "optional:file:./config/exchanges/exstub1.yml"
      - "optional:file:./config/exchanges/exstub2.yml"
      - "optional:file:./secrets/binance.yml"
      - "optional:file:./secrets/kucoin.yml"
      - "optional:file:./secrets/bitmart.yml"
      - "optional:file:./secrets/exstub1.yml"
      - "optional:file:./secrets/exstub2.yml"
      - "optional:classpath:config/base.yml"
      - "optional:classpath:config/exchanges/binance.yml"
      - "optional:classpath:config/exchanges/mexc.yml"
      - "optional:classpath:config/exchanges/xt.yml"
      - "optional:classpath:config/exchanges/coinex.yml"
      - "optional:classpath:config/exchanges/bitmart.yml"
      - "optional:classpath:config/exchanges/kucoin.yml"
      - "optional:classpath:config/exchanges/gateio.yml"
      - "optional:classpath:config/exchanges/exstub1.yml"
      - "optional:classpath:config/exchanges/exstub2.yml"
      - "optional:classpath:secrets/binance.yml"
      - "optional:classpath:secrets/kucoin.yml"
      - "optional:classpath:secrets/bitmart.yml"
      - "optional:classpath:secrets/exstub1.yml"
      - "optional:classpath:secrets/exstub2.yml"
logging:
  file:
    name: ./logs/app.log
  level:
    root: INFO
